version: "3"
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    env_file:
      - .docker.env
    volumes:
      - .:/var/www/html
    networks:
      - app-tier
    ports:
      - 80:80
    environment:
      APP_ENV: local
      CONTAINER_ROLE: app
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=oauth
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  mysqldata:
    driver: "local"